const baseurl = process.env.REACT_APP_BACKEND_URL;

const URL_LOGIN = `${baseurl}users/login`;

const URL_GET_ALL_LAPORAN_STOCK_GLOBAL_PRODUKSI = `${baseurl}`;
const URL_ADD_LAPORAN_STOCK_GLOBAL_PRODUKSI = `${baseurl}stock/report-global`;
const URL_DELETE_LAPORAN_STOCK_GLOBAL_PRODUKSI = `${baseurl}`;
const URL_UPDATE_LAPORAN_STOCK_GLOBAL_PRODUKSI = `${baseurl}`;

const URL_GET_ALL_KIRIM_SALDO_TAHUN = `${baseurl}`;
const URL_ADD_KIRIM_SALDO_TAHUN = `${baseurl}`;
const URL_DELETE_KIRIM_SALDO_TAHUN = `${baseurl}`;
const URL_UPDATE_KIRIM_SALDO_TAHUN = `${baseurl}`;

const data = {
  URL_LOGIN,
  URL_GET_ALL_LAPORAN_STOCK_GLOBAL_PRODUKSI,
  URL_ADD_LAPORAN_STOCK_GLOBAL_PRODUKSI,
  URL_DELETE_LAPORAN_STOCK_GLOBAL_PRODUKSI,
  URL_UPDATE_LAPORAN_STOCK_GLOBAL_PRODUKSI,
};

export default data;
